name = "trac-nghiem-tin-hoc"
main = "src/index.js" # Worker sẽ xử lý yêu cầu
compatibility_date = "2024-03-01"

# Cấu hình để Cloudflare hiểu đây là trang web có file tĩnh
[assets]
directory = "./public" # Thư mục chứa file index.html và questions.json
binding = "ASSETS"

[observability]
enabled = true
